### ISSUE TITLE
Wrong order of set in comments section (when comparing my output to yours)

### ISSUE THREAD

**Issue by UpwardTrajectory** [learn-co-curriculum/python-lists-lab#6]
In the "Python Lists Lab" near the end below the line "First, use the set and list functions to return a unique list of countries. Set this list equal to the variable unique_countries." You claim the correct answer should be:
unique_countries # ['Canada', 'Italy', 'USA', 'Mexico', 'Finland', 
#'Malta', 'Morocco', 'Croatia', 'Argentina', 'South Korea']

however the set() function returns the set in alphabetical order, so it should actually have Argentina at the beginning, and USA at the very end. If I'm not mistaken, it would take a fair bit of work reordering this list into the one given in the comments section quoted above.

**Comment by LoreDirick** [comment]
Hi @UpwardTrajectory:

You're right that using `set()` on `countries` generates an alphabetical set, but the goal of the exercise is to create a new list, so you should use `list(set(countries))`.

This returns a list of all the countries, in random order. So yes, your result will differ from ours, but it will not be in alphabetic order either (except for the tiny chance that the random order is alphabetical :) )

Thanks for noticing!
