### ISSUE TITLE
Changing elements

### ISSUE THREAD

**Issue by HeleneBu** [learn-co-curriculum/python-lists-lab#7]
When adding additional countries to the 'countries' list, two additions of the same value are added, instead of one. How can I fix this? I've tried the 'pop' method, but this doesn't seem to work

**Comment by mas16** [comment]
Hi HeleneBu, thanks for the post! I would recommend checking if you have run the code cell multiple times or restarting the kernel and running again. You can also consult the solution for additional clarification.
