### ISSUE TITLE
Unclear

### ISSUE THREAD

**Issue by FireFilly** [learn-co-curriculum/python-lists-lab#9]
Hi,

I am new at this. I've been studying your free data science course and I have found it very informative, but I feel I haven't been able to put into practice what I've learned while I was learning. Now,that I actually am able to start working the code myself, I have a whole bunch of stuff in my head, but it's all clogged together and I'm not sure if I'm doing it write and I don't see any tutorials or ways to verify what the correct code should look like. Is there something I'm missing?

**Comment by mas16** [comment]
Hi @FireFilly! Thanks for posting! We have added a solution to help verify what the correct code should look like. The solution can be accessed by clicking "I'm Done" in the Finish Reading box (see attached screenshot). 
<img width="1292" alt="Screen Shot 2019-08-30 at 1 49 00 PM" src="https://user-images.githubusercontent.com/31084960/64041459-85c8b180-cb2d-11e9-802e-f3eac918459b.png">
